import {
  isAngle,
  isAnglePercent,
  isLength,
  isLengthPercent,
  isNumber,
  isColor,
  isUrl,
  isNumberPercent,
  SEQ,
  POLY,
  SpaceListObj,
  SpaceFuncObj,
  CommaFuncObj,
} from "./func.js";

export default {
  transform: undefined,

  noBackdropFilter: { backdropFilter: "none" },
  noFilter: { filter: "none" },

  blur: SEQ([isLength], SpaceFuncObj("filter", "blur")),
  brightness: SEQ([isNumberPercent], SpaceFuncObj("filter", "brightness")),
  contrast: SEQ([isNumberPercent], SpaceFuncObj("filter", "contrast")),
  grayscale: SEQ([isNumberPercent], SpaceFuncObj("filter", "grayscale")),
  invert: SEQ([isNumberPercent], SpaceFuncObj("filter", "invert")),
  opacity: SEQ([isNumberPercent], SpaceFuncObj("filter", "opacity")),
  saturate: SEQ([isNumberPercent], SpaceFuncObj("filter", "saturate")),
  sepia: SEQ([isNumberPercent], SpaceFuncObj("filter", "sepia")),
  dropShadow: SEQ([isColor, isLength, isLength, isLengthPercent], SpaceFuncObj("filter", "drop-shadow")),
  hueRotate: SEQ([isAngle], SpaceFuncObj("filter", "hue-rotate")),
  filter: SEQ([isUrl], SpaceListObj("filter")),

  backdropBlur: SEQ([isLength], SpaceFuncObj("backdropFilter", "blur")),
  backdropBrightness: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "brightness")),
  backdropContrast: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "contrast")),
  backdropGrayscale: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "grayscale")),
  backdropInvert: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "invert")),
  backdropOpacity: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "opacity")),
  backdropSaturate: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "saturate")),
  backdropSepia: SEQ([isNumberPercent], SpaceFuncObj("backdropFilter", "sepia")),
  backdropDropShadow: SEQ([isColor, isLength, isLength, isLengthPercent], SpaceFuncObj("backdropFilter", "drop-shadow")),
  backdropHueRotate: SEQ([isAngle], SpaceFuncObj("backdropFilter", "hue-rotate")),
  backdropFilter: SEQ([isUrl], SpaceListObj("backdropFilter")),

  matrix: SEQ([Array(6).fill(isNumber)], CommaFuncObj("transform", "matrix")),
  matrix3d: SEQ([Array(16).fill(isNumber)], CommaFuncObj("transform", "matrix3d")),
  perspective: SEQ([isLength], CommaFuncObj("transform", "perspective")),
  rotate: SEQ([isAngle], CommaFuncObj("transform", "rotate")),
  rotateZ: SEQ([isAngle], CommaFuncObj("transform", "rotateZ")),
  rotateY: SEQ([isAngle], CommaFuncObj("transform", "rotateY")),
  rotateX: SEQ([isAngle], CommaFuncObj("transform", "rotateX")),
  translateX: SEQ([isLengthPercent], CommaFuncObj("transform", "translateX")),
  translateY: SEQ([isLengthPercent], CommaFuncObj("transform", "translateY")),
  translateZ: SEQ([isLengthPercent], CommaFuncObj("transform", "translateZ")),
  translate3d: SEQ([Array(3).fill(isLengthPercent)], CommaFuncObj("transform", "translate3d")),
  scaleX: SEQ([isNumber], CommaFuncObj("transform", "scaleX")),
  scaleY: SEQ([isNumber], CommaFuncObj("transform", "scaleY")),
  scaleZ: SEQ([isNumber], CommaFuncObj("transform", "scaleZ")),
  scale3d: SEQ([Array(3).fill(isNumber)], CommaFuncObj("transform", "scale3d")),
  skewX: SEQ([isAnglePercent], CommaFuncObj("transform", "skewX")),
  skewY: SEQ([isAnglePercent], CommaFuncObj("transform", "skewY")),
  rotate3d: SEQ([isNumber, isNumber, isNumber, isAngle], CommaFuncObj("transform", "rotate3d")),

  translate: POLY([
    SEQ([isLengthPercent], CommaFuncObj("transform", "translate")),
    SEQ([isLengthPercent, isLengthPercent], CommaFuncObj("transform", "translate")),
  ]),
  scale: POLY([
    SEQ([isNumberPercent], CommaFuncObj("transform", "scale")),
    SEQ([isNumberPercent, isNumberPercent], CommaFuncObj("transform", "scale")),
  ]),
  skew: POLY([
    SEQ([isAnglePercent], CommaFuncObj("transform", "skew")),
    SEQ([isAnglePercent, isAnglePercent], CommaFuncObj("transform", "skew")),
  ]),
};