//sequence based
function textDecoration(
  textDecorationLine = "underline",
  textDecorationStyle = "unset",
  textDecorationThickness = "unset",
  textDecorationColor = "unset") {
  return { textDecorationLine, textDecorationThickness, textDecorationStyle, textDecorationColor };
}
export default {
  textDecoration: undefined,
  textDecorationColor: undefined,
  textDecorationLine: undefined,
  textDecorationSkip: undefined,
  textDecorationSkipInk: undefined,
  textDecorationStyle: undefined,
  textDecorationThickness: undefined,
  dashedOverLine: function (args) { return textDecoration.call(this, "overline", "dashed", ...args); },
  dashedOverLineThrough: function (args) { return textDecoration.call(this, "overline line-through", "dashed", ...args); },
  dashedOverUnderLine: function (args) { return textDecoration.call(this, "overline underline", "dashed", ...args); },
  dashedOverUnderLineThrough: function (args) { return textDecoration.call(this, "overline underline line-through", "dashed", ...args); },
  dashedLineThrough: function (args) { return textDecoration.call(this, "line-through", "dashed", ...args); },
  dashedUnderLine: function (args) { return textDecoration.call(this, "underline", "dashed", ...args); },
  dashedUnderLineThrough: function (args) { return textDecoration.call(this, "underline line-through", "dashed", ...args); },
  dottedOverLine: function (args) { return textDecoration.call(this, "overline", "dotted", ...args); },
  dottedOverLineThrough: function (args) { return textDecoration.call(this, "overline line-through", "dotted", ...args); },
  dottedOverUnderLine: function (args) { return textDecoration.call(this, "overline underline", "dotted", ...args); },
  dottedOverUnderLineThrough: function (args) { return textDecoration.call(this, "overline underline line-through", "dotted", ...args); },
  dottedLineThrough: function (args) { return textDecoration.call(this, "line-through", "dotted", ...args); },
  dottedUnderLine: function (args) { return textDecoration.call(this, "underline", "dotted", ...args); },
  dottedUnderLineThrough: function (args) { return textDecoration.call(this, "underline line-through", "dotted", ...args); },
  doubleOverLine: function (args) { return textDecoration.call(this, "overline", "double", ...args); },
  doubleOverLineThrough: function (args) { return textDecoration.call(this, "overline line-through", "double", ...args); },
  doubleOverUnderLine: function (args) { return textDecoration.call(this, "overline underline", "double", ...args); },
  doubleOverUnderLineThrough: function (args) { return textDecoration.call(this, "overline underline line-through", "double", ...args); },
  doubleLineThrough: function (args) { return textDecoration.call(this, "line-through", "double", ...args); },
  doubleUnderLine: function (args) { return textDecoration.call(this, "underline", "double", ...args); },
  doubleUnderLineThrough: function (args) { return textDecoration.call(this, "underline line-through", "double", ...args); },
  wavyOverLine: function (args) { return textDecoration.call(this, "overline", "wavy", ...args); },
  wavyOverLineThrough: function (args) { return textDecoration.call(this, "overline line-through", "wavy", ...args); },
  wavyOverUnderLine: function (args) { return textDecoration.call(this, "overline underline", "wavy", ...args); },
  wavyOverUnderLineThrough: function (args) { return textDecoration.call(this, "overline underline line-through", "wavy", ...args); },
  wavyLineThrough: function (args) { return textDecoration.call(this, "line-through", "wavy", ...args); },
  wavyUnderLine: function (args) { return textDecoration.call(this, "underline", "wavy", ...args); },
  wavyUnderLineThrough: function (args) { return textDecoration.call(this, "underline line-through", "wavy", ...args); },
  overLine: function (args) { return textDecoration.call(this, "overline", "solid", ...args); },
  overLineThrough: function (args) { return textDecoration.call(this, "overline line-through", "solid", ...args); },
  overUnderLine: function (args) { return textDecoration.call(this, "overline underline", "solid", ...args); },
  overUnderLineThrough: function (args) { return textDecoration.call(this, "overline underline line-through", "solid", ...args); },
  lineThrough: function (args) { return textDecoration.call(this, "line-through", "solid", ...args); },
  underLine: function (args) { return textDecoration.call(this, "underline", "solid", ...args); },
  underLineThrough: function (args) { return textDecoration.call(this, "underline line-through", "solid", ...args); },
  blink: function (args) { return textDecoration.call(this, "blink", null, ...args); },
  grammarError: function (args) { return textDecoration.call(this, "grammar-error", null, ...args); },
  spellingError: function (args) { return textDecoration.call(this, "spelling-error", null, ...args); },
}